[jwnews]
title = "JW.org What's New"
url = "https://www.jw.org/en/whats-new/"
entrySelector = ".synopsis.borderDotted"
titleSelector = "h3"
linkSelector = "h3 a"
dateSelector = ".pubDate"

[wonger]
title = "wonger.dev posts"
url = "https://wonger.dev"
entrySelector = ".posts-container li"
titleSelector = "a"
linkSelector = "a"
