[jwvideos]
title = "JW.org New Videos"
url = "https://www.jw.org/en/library/videos/#en/home"
entrySelector = ".slick-slide"
titleSelector = "h3"
linkSelector = "h3 a"

[jwnews]
title = "JW.org What's New"
url = "https://www.jw.org/en/whats-new/"
entrySelector = ".synopsis.borderDotted"
titleSelector = "h3"
linkSelector = "h3 a"
dateSelector = ".pubDate"
